### ISSUE TITLE
Threading model introduces race conditions / seg fault with shared_ptr

### ISSUE THREAD

**Issue by haydenmc** [Glimesh/janus-ftl-plugin#6]
Seeing some race conditions crop up where shared_ptr is seg faulting during its copy constructor - should probably be using atomic_store and atomic_load when passing shared_ptr between different threads. [Relevant StackOverflow](https://stackoverflow.com/questions/48725820/segfault-when-using-shared-ptr).

Example stack from a seg fault when an active session has just been destroyed:
```
Thread 9 "janus" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe67fc700 (LWP 143841)]
0x00007ffff4d09e2e in __gnu_cxx::__atomic_add (__mem=0x55555558acc8 <janus_ice_outgoing_stats_handle+8>, __val=1) at /usr/include/c++/9/ext/atomicity.h:53
53        { __atomic_fetch_add(__mem, __val, __ATOMIC_ACQ_REL); }
(gdb) bt
#0  0x00007ffff4d09e2e in __gnu_cxx::__atomic_add(_Atomic_word volatile*, int) (__mem=0x55555558acc8 <janus_ice_outgoing_stats_handle+8>, __val=1) at /usr/include/c++/9/ext/atomicity.h:53
#1  0x00007ffff4d09eef in __gnu_cxx::__atomic_add_dispatch(_Atomic_word*, int) (__mem=0x55555558acc8 <janus_ice_outgoing_stats_handle+8>, __val=1) at /usr/include/c++/9/ext/atomicity.h:96
#2  0x00007ffff4d0ad1d in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy() (this=0x55555558acc0 <janus_ice_outgoing_stats_handle>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:139
#3  0x00007ffff4d0a4e7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) (this=0x7fffe67fb288, __r=...)
    at /usr/include/c++/9/bits/shared_ptr_base.h:737
#4  0x00007ffff4d0a393 in std::__shared_ptr<JanusSession, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<JanusSession, (__gnu_cxx::_Lock_policy)2> const&) (this=0x7fffe67fb280)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1167
#5  0x00007ffff4d0a3e1 in std::shared_ptr<JanusSession>::shared_ptr(std::shared_ptr<JanusSession> const&) (this=0x7fffe67fb280) at /usr/include/c++/9/bits/shared_ptr.h:129
#6  0x00007ffff4d09a19 in FtlStream::relayRtpPacket(RtpRelayPacket) (this=0x7fffd0001b60, rtpPacket=...) at ../FtlStream.cpp:280
#7  0x00007ffff4d09623 in FtlStream::startStreamThread() (this=0x7fffd0001b60) at ../FtlStream.cpp:236
#8  0x00007ffff4d0d45d in std::__invoke_impl<void, void (FtlStream::*)(), FtlStream*>(std::__invoke_memfun_deref, void (FtlStream::*&&)(), FtlStream*&&)
    (__f=@0x7fffd00016b0: (void (FtlStream::*)(FtlStream * const)) 0x7ffff4d08a68 <FtlStream::startStreamThread()>, __t=@0x7fffd00016a8: 0x7fffd0001b60) at /usr/include/c++/9/bits/invoke.h:73
#9  0x00007ffff4d0d377 in std::__invoke<void (FtlStream::*)(), FtlStream*>(void (FtlStream::*&&)(), FtlStream*&&)
    (__fn=@0x7fffd00016b0: (void (FtlStream::*)(FtlStream * const)) 0x7ffff4d08a68 <FtlStream::startStreamThread()>) at /usr/include/c++/9/bits/invoke.h:95
#10 0x00007ffff4d0d2c7 in std::thread::_Invoker<std::tuple<void (FtlStream::*)(), FtlStream*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x7fffd00016a8)
    at /usr/include/c++/9/thread:244
#11 0x00007ffff4d0d269 in std::thread::_Invoker<std::tuple<void (FtlStream::*)(), FtlStream*> >::operator()() (this=0x7fffd00016a8) at /usr/include/c++/9/thread:251
#12 0x00007ffff4d0d23a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (FtlStream::*)(), FtlStream*> > >::_M_run() (this=0x7fffd00016a0) at /usr/include/c++/9/thread:195
#13 0x00007ffff4b1bcb4 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff778d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff76b4103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by haydenmc** [comment]
Turns out this was a different issue.
